SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_STARTING_LIVES = 3
PLAYER_INVINCIBILITY_SECONDS = 2.0

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Asteroid splitting constants
ASTEROID_SPLIT_MIN_ANGLE = 20
ASTEROID_SPLIT_MAX_ANGLE = 50
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.2

# High score constants
INITIAL_HIGH_SCORE = 0

# Difficulty scaling constants
DIFFICULTY_START = 1.0
DIFFICULTY_MAX = 3.0
DIFFICULTY_RAMP_SCORE = 2000
ASTEROID_SPEED_MIN = 40
ASTEROID_SPEED_MAX = 100
ASTEROID_SPEED_MIN_MAX = 80
ASTEROID_SPEED_MAX_MAX = 150
SPAWN_RATE_MIN = 0.2

# Screen effects
FLASH_DURATION = 0.1
FLASH_COLOR = (255, 0, 0)
